// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.API.Database.context;

namespace TaskManager.API.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    [Migration("20211217102909_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskManager.API.Database.Entities.BaseTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedByIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TaskIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("appliedStatus")
                        .HasColumnType("int");

                    b.Property<int>("currentTaskStatus")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("reasons")
                        .HasColumnType("int");

                    b.Property<string>("taskDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("taskType")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.ToTable("BaseTasks");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.BonusSettings", b =>
                {
                    b.Property<int>("BonusSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("limit_percentage")
                        .HasColumnType("float");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BonusSettingsId");

                    b.ToTable("BonusSettings");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.BonusTask", b =>
                {
                    b.Property<int>("BonusTaskId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("one_time_bonus")
                        .HasColumnType("float");

                    b.Property<double>("salary")
                        .HasColumnType("float");

                    b.HasKey("BonusTaskId");

                    b.ToTable("BonusTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeCompensation", b =>
                {
                    b.Property<int>("CompensationTaskId")
                        .HasColumnType("int");

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("AppliedSalary")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<double>("CarBenefit")
                        .HasColumnType("float");

                    b.Property<double>("EmissionBenefit")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HomeInternetBenefit")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceBenefit")
                        .HasColumnType("float");

                    b.Property<double>("NewAdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("NewTotalMonthlyPay")
                        .HasColumnType("float");

                    b.Property<double>("PhoneBenefit")
                        .HasColumnType("float");

                    b.Property<double>("TotalMonthlyPay")
                        .HasColumnType("float");

                    b.HasKey("CompensationTaskId");

                    b.ToTable("ChangeCompensations");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeGrade", b =>
                {
                    b.Property<int>("GradeTaskId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldGrade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeTaskId");

                    b.ToTable("ChangeGrades");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeHoliday", b =>
                {
                    b.Property<int>("HolidayTaskId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HolidayEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HolidayStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubsituteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubsituteIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("holidayType")
                        .HasColumnType("int");

                    b.HasKey("HolidayTaskId");

                    b.ToTable("ChangeHolidays");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeManager", b =>
                {
                    b.Property<int>("ManagerTaskId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newCostCenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newManagerIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldCostCenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldManagerIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerTaskId");

                    b.ToTable("ChangeManagers");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeTeam", b =>
                {
                    b.Property<int>("TeamTaskId")
                        .HasColumnType("int");

                    b.Property<string>("managerIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("newCostCenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldCostCenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamTaskId");

                    b.ToTable("ChangeTeam");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeTitle", b =>
                {
                    b.Property<int>("TitleTaskId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oldTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TitleTaskId");

                    b.ToTable("ChangeTitles");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.Notifications", b =>
                {
                    b.Property<int>("notificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isRead")
                        .HasColumnType("bit");

                    b.Property<int>("tasks")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("notificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.OrganizationApprovalSettingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerType")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationApprovalSettingsId")
                        .HasColumnType("int");

                    b.Property<int>("rankNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationApprovalSettingsId");

                    b.ToTable("organizationApprovalSettingDetails");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.OrganizationApprovalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("taskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("organizationApprovalSettings");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.BonusTask", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeBonus")
                        .HasForeignKey("TaskManager.API.Database.Entities.BonusTask", "BonusTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeCompensation", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeCompensation")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeCompensation", "CompensationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeGrade", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeGrade")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeGrade", "GradeTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeHoliday", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeHoliday")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeHoliday", "HolidayTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeManager", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeManager")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeManager", "ManagerTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeTeam", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeTeam")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeTeam", "TeamTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.ChangeTitle", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.BaseTask", "BaseTask")
                        .WithOne("ChangeTitle")
                        .HasForeignKey("TaskManager.API.Database.Entities.ChangeTitle", "TitleTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseTask");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.OrganizationApprovalSettingDetail", b =>
                {
                    b.HasOne("TaskManager.API.Database.Entities.OrganizationApprovalSettings", null)
                        .WithMany("organizationApprovalSettingDetails")
                        .HasForeignKey("OrganizationApprovalSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.BaseTask", b =>
                {
                    b.Navigation("ChangeBonus");

                    b.Navigation("ChangeCompensation");

                    b.Navigation("ChangeGrade");

                    b.Navigation("ChangeHoliday");

                    b.Navigation("ChangeManager");

                    b.Navigation("ChangeTeam");

                    b.Navigation("ChangeTitle");
                });

            modelBuilder.Entity("TaskManager.API.Database.Entities.OrganizationApprovalSettings", b =>
                {
                    b.Navigation("organizationApprovalSettingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
