// <auto-generated />
using System;
using Holidays.API.Database.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Holidays.API.Migrations
{
    [DbContext(typeof(HolidaysContext))]
    partial class HolidaysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Holidays.API.Database.Entities.CompanyToEmployeeHolidays", b =>
                {
                    b.Property<int>("CompanyToEmployeeHolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccruedHolidaysPreviousYear")
                        .HasColumnType("int");

                    b.Property<int>("AgreementAnnualHolidays")
                        .HasColumnType("int");

                    b.Property<int>("AnnualHolidays")
                        .HasColumnType("int");

                    b.Property<int>("AnnualHolidaysEntitled")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmployementStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HolidaySettingsIdentitfier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeftHolidaysCurrentYear")
                        .HasColumnType("int");

                    b.Property<int>("ParentalHolidays")
                        .HasColumnType("int");

                    b.Property<int>("SickLeave")
                        .HasColumnType("int");

                    b.Property<int>("TimeOffWithoutSalary")
                        .HasColumnType("int");

                    b.Property<int>("UsedHolidaysCurrentYear")
                        .HasColumnType("int");

                    b.Property<string>("costcenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyToEmployeeHolidayId");

                    b.ToTable("CompanyToEmployeeHolidays");
                });

            modelBuilder.Entity("Holidays.API.Database.Entities.EmployeeHolidays", b =>
                {
                    b.Property<int>("EmployeeHolidayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HolidayEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HolidayStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HolidayStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubsituteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubsituteIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("costcenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("holidayType")
                        .HasColumnType("int");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeHolidayId");

                    b.ToTable("EmployeeHolidays");
                });

            modelBuilder.Entity("Holidays.API.Database.Entities.HolidayCalendar", b =>
                {
                    b.Property<int>("HolidayCalendarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fixed")
                        .HasColumnType("bit");

                    b.Property<bool>("Global")
                        .HasColumnType("bit");

                    b.Property<string>("LocalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HolidayCalendarId");

                    b.ToTable("HolidayCalendars");
                });

            modelBuilder.Entity("Holidays.API.Database.Entities.HolidaySettings", b =>
                {
                    b.Property<int>("HolidaySettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BusinessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HolidayCalendarYear")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HolidaySettingsIdentitfier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumLimitHolidayToNextYear")
                        .HasColumnType("int");

                    b.Property<string>("OrganizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HolidaySettingsId");

                    b.ToTable("HolidaySettings");
                });
#pragma warning restore 612, 618
        }
    }
}
