apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizationapi-deployment
  labels:
    app: organizationapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: organizationapi
  template:
    metadata:
      labels:
        app: organizationapi
    spec:
      containers:
        - name: organizationapi
          image: pemmexmicroservicesacr.azurecr.io/organizationapi:v1
          imagePullPolicy: Always          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__OrganizationConnection
              valueFrom:
                configMapKeyRef:
                  name: organization-connection-configmaps
                  key: db-connection-string
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: organization-connection-configmaps
                  key: IdentityUrl       
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: organizationapi-service
spec:
  type: LoadBalancer  
  selector:
    app: organizationapi
  ports:
    - targetPort: 80
      port: 80