apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeetargetsapi-deployment
  labels:
    app: employeetargetsapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: employeetargetsapi
  template:
    metadata:
      labels:
        app: employeetargetsapi
    spec:
      containers:
        - name: employeetargetsapi
          image: pemmexmicroservicesacr.azurecr.io/employeetargetsapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__EmployeeTargetsConnection
              valueFrom:
                configMapKeyRef:
                  name: employeetarget-connection-configmaps
                  key: db-connection-string
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: employeetarget-connection-configmaps
                  key: IdentityUrl      
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: employeetargetsapi-service
spec:
  type: LoadBalancer  
  selector:
    app: employeetargetsapi
  ports:
    - targetPort: 80
      port: 80