// <auto-generated />
using System;
using Compensation.API.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Compensation.API.Migrations
{
    [DbContext(typeof(CompensationContext))]
    partial class CompensationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Compensation.API.Database.Entities.Compensation", b =>
                {
                    b.Property<int>("CompensationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<double>("CarBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EmissionBenefit")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HomeInternetBenefit")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhoneBenefit")
                        .HasColumnType("float");

                    b.Property<double>("TotalMonthlyPay")
                        .HasColumnType("float");

                    b.HasKey("CompensationId");

                    b.ToTable("Compensation");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.CompensationBonuses", b =>
                {
                    b.Property<int>("compensationBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("bonusValue")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("effectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("employeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("compensationBonusId");

                    b.ToTable("CompensationBonuses");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.CompensationSalaries", b =>
                {
                    b.Property<int>("CompensationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<double>("CarBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EmissionBenefit")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HomeInternetBenefit")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhoneBenefit")
                        .HasColumnType("float");

                    b.Property<double>("TotalMonthlyPay")
                        .HasColumnType("float");

                    b.HasKey("CompensationId");

                    b.ToTable("CompensationSalaries");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.JobCatalogue", b =>
                {
                    b.Property<int>("jobCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("acv_bonus_percentage")
                        .HasColumnType("float");

                    b.Property<double>("annual_bonus")
                        .HasColumnType("float");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("maximum_salary")
                        .HasColumnType("float");

                    b.Property<double>("median_salary")
                        .HasColumnType("float");

                    b.Property<double>("minimum_salary")
                        .HasColumnType("float");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobCatalogId");

                    b.ToTable("JobCatalogues");
                });
#pragma warning restore 612, 618
        }
    }
}
