// <auto-generated />
using System;
using Compensation.API.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Compensation.API.Migrations
{
    [DbContext(typeof(CompensationContext))]
    partial class CompensationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Compensation.API.Database.Entities.Compensation", b =>
                {
                    b.Property<int>("CompensationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<double>("CarBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("EmissionBenefit")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HomeInternetBenefit")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhoneBenefit")
                        .HasColumnType("float");

                    b.Property<double>("TotalMonthlyPay")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompensationId");

                    b.ToTable("Compensation");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.CompensationSalaries", b =>
                {
                    b.Property<int>("CompensationSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<double>("CarBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EmissionBenefit")
                        .HasColumnType("float");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HomeInternetBenefit")
                        .HasColumnType("float");

                    b.Property<double>("InsuranceBenefit")
                        .HasColumnType("float");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhoneBenefit")
                        .HasColumnType("float");

                    b.Property<double>("TotalMonthlyPay")
                        .HasColumnType("float");

                    b.Property<double>("annual_bonus")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("one_time_bonus")
                        .HasColumnType("float");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompensationSalaryId");

                    b.ToTable("CompensationSalaries");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.FunctionalBudget", b =>
                {
                    b.Property<int>("FunctionalBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AdditionalAgreedPart")
                        .HasColumnType("float");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("float");

                    b.Property<string>("CostCenterIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CostCenterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Emp_Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IncreaseInCurrency")
                        .HasColumnType("float");

                    b.Property<double>("IncreaseInPercentage")
                        .HasColumnType("float");

                    b.Property<string>("JobFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NewBaseSalary")
                        .HasColumnType("float");

                    b.Property<string>("NewGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("NewTotalSalary")
                        .HasColumnType("float");

                    b.Property<string>("OrganizationCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCurrentSalary")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<double>("mandatoryPercentage")
                        .HasColumnType("float");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FunctionalBudgetId");

                    b.ToTable("FunctionalBudgets");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.JobCatalogue", b =>
                {
                    b.Property<int>("jobCatalogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("acv_bonus_percentage")
                        .HasColumnType("float");

                    b.Property<double>("annual_bonus")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("grade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jobFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("maximum_salary")
                        .HasColumnType("float");

                    b.Property<double>("median_salary")
                        .HasColumnType("float");

                    b.Property<double>("minimum_salary")
                        .HasColumnType("float");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("jobCatalogId");

                    b.ToTable("JobCatalogues");
                });

            modelBuilder.Entity("Compensation.API.Database.Entities.OrganizationBudget", b =>
                {
                    b.Property<int>("OrganizationBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalbudgetPercentage")
                        .HasColumnType("float");

                    b.Property<double>("TotalbudgetValue")
                        .HasColumnType("float");

                    b.Property<double>("budgetPercentage")
                        .HasColumnType("float");

                    b.Property<double>("budgetValue")
                        .HasColumnType("float");

                    b.Property<string>("businessIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("compulsoryPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("euro_rate")
                        .HasColumnType("float");

                    b.Property<int>("jobFunction")
                        .HasColumnType("int");

                    b.Property<string>("organizationIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrganizationBudgetId");

                    b.ToTable("OrganizationBudgets");
                });
#pragma warning restore 612, 618
        }
    }
}
