apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveyapi-deployment
  labels:
    app: surveyapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: surveyapi
  template:
    metadata:
      labels:
        app: surveyapi
    spec:
      containers:
        - name: surveyapi
          image: pemmexmicroservicesacr.azurecr.io/surveyapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__SurveyConnection
              valueFrom:
                configMapKeyRef:
                  name: survey-connection-configmaps
                  key: db-connection-string
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: survey-connection-configmaps
                  key: IdentityUrl       
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: surveyapi-service
spec:
  type: LoadBalancer  
  selector:
    app: surveyapi
  ports:
    - targetPort: 80
      port: 80