apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailapi-deployment
  labels:
    app: emailapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: emailapi
  template:
    metadata:
      labels:
        app: emailapi
    spec:
      containers:
        - name: emailapi
          image: pemmexmicroservicesacr.azurecr.io/emailapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: emailapi-service
spec:
  type: LoadBalancer  
  selector:
    app: emailapi
  ports:
    - targetPort: 80
      port: 80