apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanagerapi-deployment
  labels:
    app: taskmanagerapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: taskmanagerapi
  template:
    metadata:
      labels:
        app: taskmanagerapi
    spec:
      containers:
        - name: taskmanagerapi
          image: pemmexmicroservicesacr.azurecr.io/taskmanagerapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__TaskManagerConnection
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-connection-configmaps
                  key: db-connection-string
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-connection-configmaps
                  key: IdentityUrl
            - name: AllowedChatOrigins
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-connection-configmaps
                  key: AllowedChatOrigins                
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanagerapi-service
spec:
  type: LoadBalancer  
  selector:
    app: taskmanagerapi
  ports:
    - targetPort: 80
      port: 80