apiVersion: apps/v1
kind: Deployment
metadata:
  name: compensationapi-deployment
  labels:
    app: compensationapi
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: compensationapi
  template:
    metadata:
      labels:
        app: compensationapi
    spec:
      containers:
        - name: compensationapi
          image: pemmexmicroservicesacr.azurecr.io/compensationapi:v1
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ConnectionStrings__CompensationConnection
              valueFrom:
                configMapKeyRef:
                  name: compensation-connection-configmaps
                  key: db-connection-string
            - name: IdentityUrl
              valueFrom:
                configMapKeyRef:
                  name: compensation-connection-configmaps
                  key: IdentityUrl 
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: compensationapi-service
spec:
  type: LoadBalancer  
  selector:
    app: compensationapi
  ports:
    - targetPort: 80
      port: 80
# name